### ISSUE TITLE
Your loop iterates one time, and only for row index 1

### ISSUE THREAD

**Issue by mayisa87** [1nature/Sloth-Machine-Project#10]
https://github.com/1nature/Sloth-Machine-Project/blob/517ed0e87f438224ca8df9ae089608a379bb6ecc/Sloth%20Machine%20Project/Program.cs#L64-L72

  for (int currentRowIndex = 0; currentRowIndex < **numberOfIteration**; currentRowIndex++)
This loop makes no sense like it is.
First of all, you are using only one loop, but you should implement a generic solution, where to check all values in your slot machine.

In your code, you currently only check the middle row, but your solution should work automatically with all  line combinations. And this even if you increase your grid to an size of 1000x1000! ;)

TODO:
Implement generic solutions for this:
1. First, check all horizontal lines, if there is a winning. 
2. Second check all vertical lines for winning combinations
3. Third the two diagonal ones.
4.

How?
Use for loops like you do when filling the grid. One loop for rows, one for columns, this is the only way when checking all horizontal and vertical line values.

Here an example for horizontal lines:
```
 for (int row = 0; row < arrayNumbers.GetLength(0); row++)
 {
     //this is the code position that is done for each row!
     // like this loop of iterating through columns is done for each row
      for (int column = 0; column < arrayNumbers.GetLength(1); column++)
      {
          arrayNumbers[row, column] --> this already gives you access to the current grid value
         //TODO: Check if all values in this current line (row index = row) match.
        //check this actual grid value against the first value in this row e.g. arrayNumbers[row,0]
      } 
}
```
The same would fit for vertical, just that the row and colum loops are switched.

For diagonal you will need to think about ;)

**Comment by 1nature** [comment]
The following instructions are unclear

arrayNumbers[row, column] --> this already gives you access to the current grid value
         //TODO: Check if all values in this current line (row index = row) match.
        //check this actual grid value against the first value in this row e.g. arrayNumbers[row,0]

**Comment by mayisa87** [comment]
Maybe it helps if you draw this 2D array on a paper to visualize it better and then use a debugger for the for loops, to better understand how the nested loops are working.

![image](https://github.com/1nature/Sloth-Machine-Project/assets/130921606/bd1284ea-c1d3-47c6-a7f2-0e374a4d109d)
This is a very simplified picture of it of course. 

So the outer for loop will start at row 0, the inner loop runs through all column values in this line. 
    The TODO, or what you need to achieve is,   to check if all values are the same. 3, 1, 2 are not the same ;) But how can you find it out?

You could store the first value of the row ( in this case 3) and check if 1 and 2 are equal. If not, no winning. You can always access the first value of a row with arrayNumbers[row,0] 
     --> row = current row index and 0 the first column in this line.


If you are unsure about, how the nested loops are working or how the accessing of values in 2D array works, better join a call again, as it is very hard to describe it here :)
