### ISSUE TITLE
Implement winning check for diagonal lines

### ISSUE THREAD

**Issue by mayisa87** [1nature/Sloth-Machine-Project#23]
Depending on https://github.com/1nature/Sloth-Machine-Project/issues/13 implement the winning check for diagonal lines

**Comment by 1nature** [comment]
Does it mean I would need no separate lines of code for the diagonal ones?
Like the ones below?

for (int rowIndex = 0; rowIndex < numberOfRows; rowIndex++)
                            {
                                for (int columnIndex = 0; columnIndex < numberOfCols; columnIndex++)
                                {
                                    if (arrayNumbers[rowIndex, 0] != arrayNumbers[rowIndex, columnIndex])
                                    {
                                        diagonalLineMatch = false;
                                    }
                                }

**Comment by mayisa87** [comment]
No, sorry, that was a typing error ;) Sure you need to have a separate handling for diagonal lines.
