### ISSUE TITLE
Winning check methods are not using the array filled before!

### ISSUE THREAD

**Issue by mayisa87** [1nature/Sloth-Machine-Project#41]
https://github.com/1nature/Sloth-Machine-Project/blob/4f11bfc839f7de66a6180ce0f1338fea49300eec/Sloth%20Machine%20Project/SlotMachineMethods.cs#L122-L124

You are creating a new 2D array and then start with your winning checks on this empty, new array. This cannot work. 
You should give the int[,] as parameter from Program.cs to the SlotmachineMethods.cs

Of course the same for vertical and diagonal lines to be checked.

**Comment by 1nature** [comment]
Can you please clarify what the above comments mean? Not sure what parameters to use as you suggested

**Comment by mayisa87** [comment]
Your method should check the values of the array generated before. So somewhere at the beginning you call this method to generate your 2D filled with randim numbers:

SlotMachineMethods.GetRandom2DArray()

And you store it un a variable. So this array should be used for all further checks, to see if lines match.

Currently your new methods you created always create a new empty array and do not use the array variable of Program.cs

Therefore you will need to pass your array variable arrayGen to your methods by using a parameter.

Like 
public static int RowImplementation(int[,] slotMachineArray)

In the method you can then use this parameter "slotMachineArray" and it will hold the array values generated before
