### ISSUE TITLE
early exit and less cylces

### ISSUE THREAD

**Issue by incredibleLeitman** [1nature/Sloth-Machine-Project#55]
although this is a performance optimization I just wanna show you something:
https://github.com/1nature/Sloth-Machine-Project/blob/cee2732cd192f92170a12fb7918aca74c54d3336/Sloth%20Machine%20Project/SlotMachineMethods.cs#L96-L111

In this case, if the inner loop detects a non-matching column there is no need to further checks the following cols because the line can never be a full match again -> here you could use a break.
Also, think about if the inner loop really needs to start at 0? 😏 For the first iteration you compare if col 0 equals col 0 which would always be true right?

*HOWEVER* 👆 not that this function has a logical error!
If for example in the first line the first two cols don't match, you set the flag to false,
but you never set it back to true 🤷 
This means, that even if the second line would be a full matching row this implementation would not detect it.

This issue applies for row, col and diagonals

**Comment by 1nature** [comment]
Thank you for your comments. Problem is that I need help with debugging. Most times, I struggle to debug my codes. I would often resolve to imagining them to address tutor comments. I think a coder in my level would need to be able to debug codes to address the above comments. Can you spare some time to run me through debugging of codes? It would make my life easy with coding going forward. I am sorry for asking for more.

**Comment by mayisa87** [comment]
Still you have a logic error in this method.

You initialilze your lineMatch with false. Let's imagine this grid:
1 1 2
1 1 1
2 3 3

You start in row = 0, and 1 and 1 match, 1 and 1 match, 2 and 1 don't match, You fall into your if, and check if lineMatch is false, if yes, you break.

Next line:
1 and 1, match. 1 and 1 match, 1 and 1 match. So you never enter your if and oustide you ask if lineMatch is true, but how should it, as it is never set to true at all?

So as discussed in the call, the boolean should be used like a button. You start with button pressed (lineMatchi = true) as you assume a match. You loop through your row, and if you detect a mismatch, you set lineMatch false and break the loop. Your button is no longer pressed.

if you have a line full matching, you will not detect a mismatch and your lineMatch stays set to true, so your outer if will match then.

So it is more like toggling. Start with true, set it to false only if there is a mismatch. Reset the boolean to true at each line start.

**Comment by mayisa87** [comment]
![image](https://github.com/1nature/Sloth-Machine-Project/assets/130921606/2791c8e6-8b57-4b5f-9217-b599c6277128)

As you can see, I filled the array hardcoded with 2 winning lines in horizontal, and added a simple output to let you see what happens. The logic does not detected the 2 winning lines at all. There is still something wrong about setting your boolean variables. 
As recommended in the live call. You should debug the loops and for testing try to fill some hardcoded values to your 2D array. So you can test all kind of combinations.

I just outcommented the array filling algorithm and return instead an hardcoded 2D array back in your filling method:


            int[,] arrayNumbers = {{1,2,1},
                                   {1,1,1 },
                                   {1,1,1 } } ;
