### ISSUE TITLE
Confusing user commentary

### ISSUE THREAD

**Issue by 1nature** [1nature/Sloth-Machine-Project#63]
In my current code, if my user decides to bet "ALL" - ALL suggests that the user wants to make a bet for both horizontal and vertical column matches, two commentaries are given to the user about whether they won or not. I think this is confusing to run two commentaries. I am trying to rework the code to prevent this. Kindly provide any suggestion. Thanks

**Comment by mayisa87** [comment]
Confusing for me is, first to choose the bet amount, and then the line type. It would be more intuitive to me, first asking the user which line type to play, and then how many lines of it.
