### ISSUE TITLE
Implement a generic solution

### ISSUE THREAD

**Issue by mayisa87** [1nature/Sloth-Machine-Project#7]
https://github.com/1nature/Sloth-Machine-Project/blob/beba8259fc144a20eb1a517f5bf5610e415f19c9/Sloth%20Machine%20Project/Program.cs#L56-L61

Always try to be as generic as possible. Currently you are checking the values to be equal hardcoded. Imagine you grid would be of size 100x100. It wouldn't be possible anymore to do the checks like this.

Think about an implementation by using loops to iterate through your values in array and check if all values match.

**Comment by 1nature** [comment]
This is not my latest code. I revised this based on your earlier comments
