### ISSUE TITLE
This could be moved to a method

### ISSUE THREAD

**Issue by mayisa87** [1nature/Sloth-Machine-Project#75]
https://github.com/1nature/Sloth-Machine-Project/blob/61daad0d784abb326bc3531afd2d57a49334f771/Sloth%20Machine%20Project/Program.cs#L72-L82

https://github.com/1nature/Sloth-Machine-Project/blob/61daad0d784abb326bc3531afd2d57a49334f771/Sloth%20Machine%20Project/Program.cs#L90-L101

https://github.com/1nature/Sloth-Machine-Project/blob/61daad0d784abb326bc3531afd2d57a49334f771/Sloth%20Machine%20Project/Program.cs#L108-L118

Just saw, that here you could write a logic method, like public int CheckOnWinningAmount(int lineMatchingCount)

So a method where you give as parameter the current bank amount, and check on the amount of lines matching, if there was a match you could return back the lineMatchingCount and increase your bank variable with it, if it was a dismatch you can return a minus value for example and your bank amount will be automatically decreased.

**Comment by 1nature** [comment]
Some confusion for me here....the method you suggested above has "lineMatchingCount" as a parameter. In the second line, you also suggested "current bank amount" as a parameter. Can you clarify for me? Thanks

**Comment by mayisa87** [comment]
Yes, mixes up two options here it seems 

So you everytime you check for winnings you get back ab amount of lines won and check if this count is greater than LINE_MATCH_COUNTER. SO if you move this logic into a mrthod you could give the amount of lines won to it as parameter. Inside do your if statement, and return whether the line amount back or -line_match_counter in case of no win.

In the Main() method increase bank variable with the return value
